# Generated by Django 4.2.3 on 2023-07-24 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UI", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="flash",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="message",
            name="scroll",
            field=models.CharField(default=False, max_length=20),
            preserve_default=False,
        ),
    ]
