# Generated by Django 4.2.3 on 2023-07-24 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UI", "0002_message_flash_message_scroll"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="flash",
            field=models.BooleanField(default=False),
        ),
    ]
