# Generated by Django 4.2.3 on 2023-07-25 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UI", "0003_alter_message_flash"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="display_time",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
