# Generated by Django 4.2.3 on 2023-07-28 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UI', '0005_rename_flash_message_flash1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='line1',
            field=models.TextField(max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='line2',
            field=models.TextField(max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='line3',
            field=models.TextField(max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='line4',
            field=models.TextField(max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='line5',
            field=models.TextField(max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='line6',
            field=models.TextField(max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='line7',
            field=models.TextField(max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='line8',
            field=models.TextField(max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='scroll1',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='scroll2',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='scroll3',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='scroll4',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='scroll5',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='scroll6',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='scroll7',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='scroll8',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='transition_time1',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='transition_time2',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='transition_time3',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='transition_time4',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='transition_time5',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='transition_time6',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='transition_time7',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='transition_time8',
            field=models.IntegerField(null=True),
        ),
    ]
