# Generated by Django 4.2.3 on 2023-07-28 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UI', '0006_alter_message_line1_alter_message_line2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='transition_time1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='message',
            name='transition_time2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='message',
            name='transition_time3',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='message',
            name='transition_time4',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='message',
            name='transition_time5',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='message',
            name='transition_time6',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='message',
            name='transition_time7',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='message',
            name='transition_time8',
            field=models.IntegerField(default=0),
        ),
    ]
