# Generated by Django 4.2.3 on 2023-07-28 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UI', '0007_alter_message_transition_time1_and_more'),
    ]

    operations = [
    ]
