# Generated by Django 4.2.3 on 2023-08-01 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UI', '0008_auto_20230728_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='voice_file_name',
            field=models.TextField(default='V500903'),
        ),
    ]
