# Generated by Django 4.2.4 on 2023-08-04 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UI', '0009_message_voice_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='scroll1',
            field=models.CharField(default='None', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='scroll2',
            field=models.CharField(default='None', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='scroll3',
            field=models.CharField(default='None', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='scroll4',
            field=models.CharField(default='None', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='scroll5',
            field=models.CharField(default='None', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='scroll6',
            field=models.CharField(default='None', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='scroll7',
            field=models.CharField(default='None', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='scroll8',
            field=models.CharField(default='None', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='transition_time1',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='message',
            name='transition_time2',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='message',
            name='transition_time3',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='message',
            name='transition_time4',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='message',
            name='transition_time5',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='message',
            name='transition_time6',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='message',
            name='transition_time7',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='message',
            name='transition_time8',
            field=models.IntegerField(default=2),
        ),
    ]
