# Generated by Django 4.2.4 on 2023-08-09 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UI', '0012_alter_message_line1_alter_message_line10_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='title',
            field=models.CharField(max_length=19),
        ),
    ]
